### ISSUE TITLE
Module causes some weird device issues

### ISSUE THREAD

**Issue by jbro129** [stylemessiah/AppDataIsolation#2]
I've been using this module for about a week now and I've noticed some issues.
My device is a Galaxy s20 Ultra (G988U) running android 11.

1. Auto-Rotate completely breaks. Once I disable the module auto-rotate works again.
2. Image caching for apps doesn't work. For example: I cleared Telegrams cache and none of the server icons or peoples profile pictures load. Again, once disabling the module and rebooting the images load.
3. Some apps on my homescreen have a grey or completely transparent icon inside of folders. Sometimes it takes a few seconds for the icons to come back, but sometimes they don't at all. This occurs with the OneUI home launcher and Nova launcher.
4. File browsing apps lose permissions to R/W files. I've noticed that when using Root Explorer that when trying to view a text file in its built-in text viewer it tells me along the lines of "Unable to view, your device may not be rooted". This occurs with files on my devices storage as well as in root directories. Same goes for trying to unzip, zip, view any kind of file, etc.

These are just some issues I've comes across while using the module. I don't know if they are unintended issues based on my device or if anybody else is having these problems.

**Comment by stylemessiah** [comment]
Cheers I'm on stock A12 on my S20+ 5G and haven't seen any issues yet. But
I will notify folks later today when I'm home to be on the lookout

Yours is the first report of anything hinky at all

**Comment by jbro129** [comment]
Strange... Maybe it has to do with android 11? If your s20+ isn't having any issues with this module then I'm not sure why I am.

**Comment by stylemessiah** [comment]
Like many things in droid land, one of many mysteries :)

**Comment by stylemessiah** [comment]
Added a Known/Suspected Issue section to Readme, and included your report verbatim there

Lets see if anyone else reports anything similar. Conversely if you find its attributable to something else, please let me know.

Issue will remain open for a fair period in case other reports come in

**Comment by stylemessiah** [comment]
Any news?

**Comment by jbro129** [comment]
I updated to an Android 12 rom and none of the issues occur anymore. Droid land
