### ISSUE TITLE
The description describe what module does is not understandable for other users

### ISSUE THREAD

**Issue by HuskyDG** [stylemessiah/AppDataIsolation#3]
As title said, "The description describe what module does is not understandable for other users" and not many user understand what is "An attempt to block access, by other apps, to the private data directories for all supported API's ". You better rewrite description in the better way so that everyone can understand and no more stupid questions what module does.

**Comment by stylemessiah** [comment]
Closed for being insulting (a second time). And there wont be a 3rd. We have already been down this road.

The sentence perfectly describes exactly what the module does, in a very compact way 

* blocks access
* by other apps
* to private data directories

You seem to be the only person with a problem with this....

Please, if you dont have anything nice to say, keep your corrosive thoughts to yourself. Whiloe i have had my own opinions on your work, i have been fair and balanced, and argued points, not you personally. Ive even tried where i felt i could to extend an olive branch and ask permission to include links to your work, and been ignored. I recommend it, even try and positively comment. You seem to to be very much into making personal attacks. They wont be tolerated here.

Make better choices.

**Comment by stylemessiah** [comment]
> > Closed for being insulting (a second time). And there wont be a 3rd. We have already been down this road.
> 
> I'm sorry if i am talking like this about I am not going to insult but it seems not many users really understand after reading README.md

Mate theres an entire article attached to the readme....that describe sit in a more expansive way that im not goign to be able to do better with

i was asked by a the senior member to package this, they sent me the linked article, i wasnt really interested in making it, i was asked as a favour and they had already promised an entire Telegram Group that i would do it (without asking me first). That is the honest truth. If i could figure it out in a few minutes of having no interest at all, then i felt i have done my best as describing it in a compact succinct way, and including the original article which discusses the theory behind it. Id argue thats a fair enogh description and bonus of including the original article.

Can we just get along please....

**Comment by stylemessiah** [comment]
Please realise i did acknowledge your own version for A11- devices, and reached out to congratulate you, and even ask permission to link your work from my own a little while ago, and never got a reply. Out of respect i didnt link.

https://forum.xda-developers.com/t/hide-my-applist-a-brief-guide.4519731/post-87815033

**Comment by stylemessiah** [comment]
I eaeleir modified the title to:

An attempt to block access, by other apps, to the private data directories for all supported API levels (30+/Android 11+)

which is very close, how about:

An attempt to block access to all supported SDK apps, from accessing other apps' private data on Android 11+ (API 30+)

**Comment by stylemessiah** [comment]
> Android 11+ has `/data/data` isolation but if apps are not adopted to Android 11, it will not isolate `/data/data`. This module emforces `/data/data` isolation. Is that right?

That is my understanding as explained ot me, and linked in the article.....it removes the targetted API requirement or in the words enforces universal isolation

**Comment by stylemessiah** [comment]
> > That is my understanding as explained to me, and linked in the article.....it removes the targetted API requirement or in the words enforces universal isolation
> 
> But `module.prop` does not mention about Android 11+:
> 
> https://github.com/stylemessiah/AppDataIsolation/blob/1f9cbc86eefebf1cdad3ddeadbd3e4a761cd88cf/module.prop#L6

readme and module.prop updated to reflect this:

An attempt to block apps from accessing other apps' private data on Android 11+ (API 30+)

**Comment by stylemessiah** [comment]
It also might have helped yesterday if you'd told me that you had users in your channel on Telegram who were confused about the title (i just found them, i rarely venture on TG these days), as i was confused wondering where people were getitng ocnfused, because ive literally no one contact me abotu this module . Makes a lot more sense now why you made the request!....
